Action releases migration implementation
actions-on-packages/gh-action-release pull request #1
Opened 2022-11-25 13:33 UTC by raju-dasupally

Implemented CLI utility for migrating action releases as Action packages

2022-11-28 08:15 UTC, srahul3 requested changes
Few minor comments

2022-11-28 08:15 UTC, srahul3 commented on README.md
> +	$ gh action-release migrate -r github/js-action
Cosmetic: Can we make the example repo anonymous?

2022-11-28 08:15 UTC, srahul3 commented on Service/release_action_service.go
> +		logger.LogInfo("unable to retrieve tag list from GHCR ")
LogError in place of logInfo. Also not to ignore the error message from the response

2022-11-28 08:15 UTC, srahul3 commented on Service/release_action_service.go
> +	// logger.LogError(string(responseBody))
Remove the commented code

2022-11-28 08:15 UTC, srahul3 commented on Service/release_action_service.go
> +		return tagListResponse, err
tagListResponse or response?

2022-11-28 08:15 UTC, srahul3 commented on Service/release_action_service.go
> +	listReleasePath := fmt.Sprintf("repos/%s/%s/releases?per_page=20&page=1", repo.Owner(), repo.Name())
We may want to recursively call this until we have next page available.

2022-11-28 14:10 UTC, vinaykanamarlapudi commented on Service/release_action_service.go
> +	var tagListUrl = fmt.Sprintf("https://ghcr.io/v2/%s/%s/tags/list", repo.Owner(), repo.Name())
Does this tag list return paginated list or it will return entire list (even if there are 100 entries)

2022-11-28 14:14 UTC, vinaykanamarlapudi commented on Service/release_action_service.go
> +func GetExistingReleases(repo ghRepo.Repository) ([]models.ReleaseApiResponse, error) {
This function should take page number as an input, otherwise we will miss out releases if a repo has more than 20 releases(which is quite possible).

2022-11-28 14:15 UTC, vinaykanamarlapudi commented on Service/release_action_service.go
> +	listReleasePath := fmt.Sprintf("repos/%s/%s/releases?per_page=20&page=1", repo.Owner(), repo.Name())
per_page can be declared as a constant

2022-11-28 14:21 UTC, vinaykanamarlapudi commented on cmd/migrate.go
> +
Could you add some comments to describe the process for better readability

2022-11-28 14:22 UTC, vinaykanamarlapudi commented
Please add unit test

2022-11-28 14:23 UTC, vinaykanamarlapudi requested changes
Could you add unit test and handle pagination for existing releases function

2022-11-30 09:11 UTC, raju-dasupally commented on Service/release_action_service.go
> +		return tagListResponse, err
tagListResponse only. This method should returns TagListResponse. In this case, we are returning an error along with empty response. The caller supposed to check if this method returned error or response. If error is present, its a failure

2022-11-30 09:16 UTC, raju-dasupally commented on Service/release_action_service.go
> +func GetExistingReleases(repo ghRepo.Repository) ([]models.ReleaseApiResponse, error) {
otherwise, may be this function should take care of pagination itself, accumulate results and return to its caller.

2022-12-01 14:45 UTC, raju-dasupally commented on Service/release_action_service.go
> +		logger.LogInfo("unable to retrieve tag list from GHCR ")
done

2022-12-01 14:45 UTC, raju-dasupally commented on Service/release_action_service.go
> +	// logger.LogError(string(responseBody))
done

2022-12-01 14:46 UTC, raju-dasupally commented on Service/release_action_service.go
> +		return tagListResponse, err
returning empty tagListResponse here along with error, when error is present, it means that the request is failed, so returning empty list

2022-12-01 14:46 UTC, raju-dasupally commented on Service/release_action_service.go
> +	listReleasePath := fmt.Sprintf("repos/%s/%s/releases?per_page=20&page=1", repo.Owner(), repo.Name())
done

2022-12-01 14:46 UTC, raju-dasupally commented on Service/release_action_service.go
> +	var tagListUrl = fmt.Sprintf("https://ghcr.io/v2/%s/%s/tags/list", repo.Owner(), repo.Name())
done

2022-12-01 14:46 UTC, raju-dasupally commented on Service/release_action_service.go
> +func GetExistingReleases(repo ghRepo.Repository) ([]models.ReleaseApiResponse, error) {
done

2022-12-01 14:47 UTC, raju-dasupally commented on Service/release_action_service.go
> +	listReleasePath := fmt.Sprintf("repos/%s/%s/releases?per_page=20&page=1", repo.Owner(), repo.Name())
done

2022-12-01 14:47 UTC, raju-dasupally commented on cmd/migrate.go
> +
done

2022-12-02 03:22 UTC, srahul3 submitted a review, later dismissed
LGTM ✅

2022-12-02 05:10 UTC, raju-dasupally commented
> Could you add unit test and handle pagination for existing releases function

will followup with another PR for unit tests

2022-12-02 05:56 UTC, vinaykanamarlapudi commented
> Could you add unit test and handle pagination for existing releases function

It is always good to have unit test in the same PR so that we don't miss the context.

2022-12-08 12:11 UTC, vinaykanamarlapudi submitted a review, later dismissed
Remove redundant and unwanted files

2022-12-08 12:17 UTC, raju-dasupally commented
> Remove redundant and unwanted files

Done.

2022-12-08 12:25 UTC, srahul3 approved these changes
LGTM ✅

2022-12-08 12:25 UTC, srahul3 commented on Service/release_action_service.go
> +	for true {
will while statement makes better sense here?

2022-12-08 12:26 UTC, raju-dasupally commented on Service/release_action_service.go
> +	for true {
No `while` in golang 😄

2022-12-08 12:27 UTC, merged